version: 2
updates:
    # Fetch and update latest `npm` packages
    - package-ecosystem: npm
      open-pull-requests-limit: 0
      schedule:
          interval: daily
          time: "00:00"
      directory: "/"
      target-branch: dev
    # Fetch and update latest `github-actions` pkgs
    - package-ecosystem: github-actions
      directory: "/"
      target-branch: dev
      schedule:
          interval: daily
          time: "00:00"
      open-pull-requests-limit: 0
